LAB-155: Code editor backend - Foundations
RN35/CS_506 pull request #1
Opened 2022-06-01 20:41 UTC by RN35

# Proposed Changes

- Initial setup for an express web app
- '/run' endpoint that takes 'language' and 'code' as an input and returns results

# Jira Stories

- [LAB-155](https://oregonstate-innovationlab.atlassian.net/browse/LAB-155)

# Checklist

- [x] This has been tested
- [x] Self-documenting code
- [x] Code is linted

# Instructions to review
## How to Run
- Clone the repository: `git clone git@github.com:RN35/CS_506.git`
- Change dir: `cd CS_506`
- Checkout branch feat/backend-setup: `git checkout feat/backend-setup`
- Run Docker Desktop
- Build docker container: `docker build . -t cs_506/backend`
- Run docker container: `docker run -p 8080:8080 -d cs_506/backend`

## How to Validate
- Send a POST request
  - endpoint: `http://localhost:3001/run`
  - body: `{ language: 'py', code: "print(f'Hello World { 3 + 6 }')" }`
    - language -> optional (defaults -> 'py'), code -> mandatory
- Suggested testing
  - Pass both language and code
  - Pass only code 
  - Pass only language 
  - Submit code that has an error 

## How to Cleanup
- Exit docker container and delete image: `docker image rm -f cs_506/backend`

# Screenshots 

## Pass both language and code
<img width="1440" alt="Screen Shot 2022-06-01 at 1 38 39 PM" src="https://user-images.githubusercontent.com/15828512/171497523-4116676b-9dae-4db1-891b-66cc1c959ba6.png">

## Pass only code
<img width="1440" alt="Screen Shot 2022-06-01 at 1 39 16 PM" src="https://user-images.githubusercontent.com/15828512/171497584-7ade4033-c333-481f-831f-6239bfd44aab.png">

## Pass only language
<img width="1440" alt="Screen Shot 2022-06-01 at 1 39 28 PM" src="https://user-images.githubusercontent.com/15828512/171497601-4fe08e8e-977d-4fc9-bc42-db63b3d5375e.png">

## Submit code that has an error 
<img width="1440" alt="Screen Shot 2022-06-01 at 1 39 57 PM" src="https://user-images.githubusercontent.com/15828512/171497624-37f8e6f6-f2e8-455e-9b7b-705f8012e6ac.png">

2022-06-02 02:50 UTC, wbraynen requested changes
Left some questions.

2022-06-02 02:50 UTC, wbraynen commented on backend/index.js
> +app.post('/run', async (req, res) => {
This might be personal preference, but I find express.js code much easier to read, when it scales to include more routes, when it doesn't use closures.  For an example, [see here](https://github.com/wbraynen/lighthouse-api/blob/master/app.js).

That way, it's easy to see what the endpoints are.

2022-06-02 02:50 UTC, wbraynen commented on backend/index.js
> +  }
Clean up this bit of code so it's easier to follow.  Below are some suggestions.  Here goes...

This might be a linting preference, but I find code easier to read when the formatting has a little room to breathe.  

For example, the comment "// runs the saved file"—does that comment apply to line 23 only or to lines 23-24?  Here is an example of how to format it if it's just line 23:
```
// takes the input code and saves it to a file
const filepath = await generateFile(language, code);

// runs the saved file
const output = await executePy(filepath);

return res.json({ filepath, output });
```
Here is an example of how to format it if it's lines 23-24:

```
// takes the input code and saves it to a file
const filepath = await generateFile(language, code);

// runs the saved file
const output = await executePy(filepath);
return res.json({ filepath, output });
```

Either way, now it's clear which it is.

That said, why not make it self-documenting code and get rid of comments altogether?  (Code evolves while comments go stale, so...)  For example:

```
const file_path = await saveCodeToFile(code, language);
const output = await executeCode(file_path);
return res.json({ filepath, output });
```
Also, in `generateFile(language, code);` you are asking for the language, but in the very next line it's `executePy`.  "Py" means Python?  If so, which is it?  The language is always Python or not always Python?  (Line 15 suggests that it's always Python; but if so, then ???)

2022-06-02 02:50 UTC, wbraynen commented on backend/index.js
> +});
For readability, I would skip a line before `app.listen`.  Like so:
```
});

app.listen(8080, () => {
   console.log('Listening on port 8080!');
 });
```

Also, just curious, how is it different from the following?
```
app.listen(8080)
console.log('Listening on port 8080!')
```
Is it just in case the `listen` call fails?

2022-06-02 02:50 UTC, wbraynen commented on backend/generateFile.js
> +const generateFile = async (format, code) => {
This is `async`, but at the call site it's `await`.  Does "await" mean to make a blocking call?  If so, why make it asynchronous if you are just going to block and wait until it returns?

Also, can this just be written as a function?  Does it have to be a closure because of the await?  (Functions are generally easier to read.)

2022-06-02 02:50 UTC, wbraynen commented on backend/executePy.js
> +const executePy = (filepath) => new Promise((resolve, reject) => {
Can this be a function?  Does it have to be a closure because of the `Promise`?

2022-06-02 02:50 UTC, wbraynen commented on backend/generateFile.js
> +const fs = require('fs');
What's `fs`?  File system?

2022-06-02 02:50 UTC, wbraynen commented on backend/generateFile.js
> +}
I have some guesses, but I can't say I fully understand what's going on here.  I could use some comments or self-documenting code here.

2022-10-07 05:45 UTC, RN35 commented on backend/index.js
> +app.post('/run', async (req, res) => {
Understood. Addressed.

2022-10-07 05:47 UTC, RN35 commented on backend/index.js
> +  }
- Added comments
- Changed func names and file names to make it self-documenting

2022-10-07 05:47 UTC, RN35 commented on backend/index.js
> +});
Addressed

2022-10-07 05:48 UTC, RN35 commented on backend/generateFile.js
> +const generateFile = async (format, code) => {
It was not required. Made it into synchronized call i.e. blocking. Rewrote it as a function.

2022-10-07 05:48 UTC, RN35 commented on backend/executePy.js
> +const executePy = (filepath) => new Promise((resolve, reject) => {
It was not required. Made it into synchronized call i.e. blocking. Rewrote it as a function.

2022-10-07 05:48 UTC, RN35 commented on backend/generateFile.js
> +}
Added comments. Addressed.

2022-10-07 19:09 UTC, supreethavadhani approved these changes

2022-10-07 21:03 UTC, wbraynen approved these changes
Use the "squash and merge" button when merging this PR.

2022-10-07 22:12 UTC, merged